# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bollinger Bands
#'
#' @param price A numeric vector of prices
#' @param n The period for the moving average
#' @param sd The number of standard deviations for the bands
#' @return A list containing the lower band, moving average, upper band, and percentage B
#' @export
bb <- function(price, n, sd = 2L) {
    .Call(`_dmplot_bb`, price, n, sd)
}

#' Exponential Moving Average
#'
#' @param price A numeric vector of prices
#' @param n The period for the EMA
#' @param wilder Whether to use Wilder's smoothing
#' @return A numeric vector containing the EMA values
#' @export
ema <- function(price, n, wilder = FALSE) {
    .Call(`_dmplot_ema`, price, n, wilder)
}

#' Fibonacci Retracement Levels
#' Calculate the Fibonacci retracement levels for a given price range
#' @param high The high price
#' @param low The low price
#' @return A list containing the retracement levels and prices
#' @export
fib <- function(high, low) {
    .Call(`_dmplot_fib`, high, low)
}

#' Moving Average Convergence Divergence (MACD)
#'
#' @param price A numeric vector of prices
#' @param s The short-term period
#' @param l The long-term period
#' @param k The signal line period
#' @param percent Whether to return the MACD as a percentage
#' @return A list containing the MACD and signal line values
#' @export
macd <- function(price, s, l, k, percent = TRUE) {
    .Call(`_dmplot_macd`, price, s, l, k, percent)
}

#' Momentum
#'
#' @param price A numeric vector of prices
#' @param n The period for momentum calculation
#' @return A numeric vector containing the momentum values
#' @export
mom <- function(price, n) {
    .Call(`_dmplot_mom`, price, n)
}

#' Monte Carlo Simulation in C++
#'
#' This function performs a Monte Carlo simulation for price movements using C++.
#'
#' @param seed_price numeric. The starting price for the simulation.
#' @param daily_vol numeric. The daily volatility of the price movements.
#' @param num_sims integer. The number of simulation paths to generate.
#' @param num_days integer. The number of days to simulate for each path.
#'
#' @return A list containing two data frames:
#'   \item{simulations}{A data frame with columns 'close' (simulated prices) and 'simulation' (simulation index)}
#'   \item{end_prices}{A data frame with columns 'close' (final prices) and 'simulation' (simulation index)}
#'
#' @details
#' This function uses a geometric Brownian motion model to simulate price movements.
#' For each simulation path, it generates daily returns using a normal distribution
#' with mean 0 and standard deviation equal to the provided daily volatility.
#' The function is implemented in C++ for improved performance, especially for
#' large numbers of simulations or long time horizons.
#'
#' @examples
#' \dontrun{
#' results <- monte_carlo(seed_price = 100, daily_vol = 0.02, num_sims = 1000, num_days = 30)
#' head(results$simulations)
#' head(results$end_prices)
#' }
#'
#' @export
monte_carlo <- function(seed_price, daily_vol, num_sims, num_days) {
    .Call(`_dmplot_monte_carlo`, seed_price, daily_vol, num_sims, num_days)
}

#' Rate of Change (ROC)
#'
#' @param price A numeric vector of prices
#' @param n The period for ROC calculation
#' @param type The type of ROC calculation: 'c' for continuous (default) or 'd' for discrete
#' @return A numeric vector containing the ROC values
#' @export
roc <- function(price, n, type = 'c') {
    .Call(`_dmplot_roc`, price, n, type)
}

#' Relative Strength Index (RSI)
#'
#' @param price A numeric vector of prices
#' @param n The period for RSI calculation
#' @param method The method for average calculation: 'e' for EMA (default) or 's' for SMA
#' @return A numeric vector containing the RSI values
#' @export
rsi <- function(price, n, method = 'e') {
    .Call(`_dmplot_rsi`, price, n, method)
}

#' Simple Moving Average (SMA)
#'
#' @param price A numeric vector of prices
#' @param n The period for SMA calculation
#' @return A numeric vector containing the SMA values
#' @export
sma <- function(price, n) {
    .Call(`_dmplot_sma`, price, n)
}

