# https://github.com/Appsilon/shiny.blueprint
name: pkgdown
on: push
permissions:
  contents: write
jobs:
  main:
    name: Build and publish website
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Print R session info
        run: |
          Rscript -e "sessionInfo()"
          Rscript -e "installed.packages()[, c('Package', 'Version')]"

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, github::dereckmezquita/kucoin, local::.

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: List package contents
        run: |
          ls -R

      - name: Build package
        run: |
          R CMD build . --no-build-vignettes
          R CMD INSTALL --build .
          R CMD check --no-manual --no-tests --no-examples --no-codoc --no-vignettes --no-build-vignettes *tar.gz

      - name: Show check results
        if: always()
        run: |
          find . -name "00check.log" -exec cat {} \;
          find . -name "00install.out" -exec cat {} \;

      - name: Show error logs
        if: failure()
        run: |
          find . -name "*.Rout" -exec cat {} \;
          find . -name "*.fail" -exec cat {} \;

      - name: Deploy to branch
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        shell: Rscript {0}
        run: pkgdown::deploy_to_branch(branch = "bot/github-pages")